# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='ImageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=40)),
                ('height', models.IntegerField(default=40)),
                ('z', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='view',
            name='viewController',
        ),
        migrations.RemoveField(
            model_name='viewcontroller',
            name='question_text',
        ),
        migrations.DeleteModel(
            name='View',
        ),
        migrations.AddField(
            model_name='imageview',
            name='viewController',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.ViewController'),
        ),
    ]
