# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_auto_20171026_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=40)),
                ('height', models.IntegerField(default=40)),
                ('z', models.IntegerField(default=0)),
                ('normal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Button_normal', to='vision.Image')),
                ('viewController', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.ViewController')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
