# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0006_auto_20171026_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewcontroller',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
