# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0007_auto_20171026_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='color',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='imageview',
            name='color',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='normal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_normal', to='vision.Image'),
        ),
        migrations.AlterField(
            model_name='imageview',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.Image'),
        ),
    ]
