# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0008_auto_20171026_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=40)),
                ('height', models.IntegerField(default=40)),
                ('z', models.IntegerField(default=-1)),
                ('color', models.CharField(blank=True, max_length=9, null=True)),
                ('titel', models.CharField(max_length=50)),
                ('viewController', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.ViewController')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
