# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0009_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='titel',
            new_name='text',
        ),
        migrations.AddField(
            model_name='label',
            name='fontSize',
            field=models.IntegerField(default=14),
        ),
    ]
