# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0011_auto_20171027_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.Button'),
        ),
        migrations.AddField(
            model_name='imageview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.ImageView'),
        ),
        migrations.AddField(
            model_name='label',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.Label'),
        ),
        migrations.AlterField(
            model_name='button',
            name='color',
            field=models.CharField(default='#efeff4', max_length=7),
        ),
        migrations.AlterField(
            model_name='imageview',
            name='color',
            field=models.CharField(default='#efeff4', max_length=7),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default='#efeff4', max_length=7),
        ),
        migrations.AlterField(
            model_name='label',
            name='fontColor',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
