# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0012_auto_20171027_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=40)),
                ('height', models.IntegerField(default=40)),
                ('z', models.IntegerField(default=-1)),
                ('color', models.CharField(default='#efeff4', max_length=7)),
                ('viewController', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.ViewController')),
            ],
        ),
        migrations.RemoveField(
            model_name='button',
            name='color',
        ),
        migrations.RemoveField(
            model_name='button',
            name='height',
        ),
        migrations.RemoveField(
            model_name='button',
            name='id',
        ),
        migrations.RemoveField(
            model_name='button',
            name='name',
        ),
        migrations.RemoveField(
            model_name='button',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='button',
            name='viewController',
        ),
        migrations.RemoveField(
            model_name='button',
            name='width',
        ),
        migrations.RemoveField(
            model_name='button',
            name='x',
        ),
        migrations.RemoveField(
            model_name='button',
            name='y',
        ),
        migrations.RemoveField(
            model_name='button',
            name='z',
        ),
        migrations.RemoveField(
            model_name='imageview',
            name='color',
        ),
        migrations.RemoveField(
            model_name='imageview',
            name='height',
        ),
        migrations.RemoveField(
            model_name='imageview',
            name='id',
        ),
        migrations.RemoveField(
            model_name='imageview',
            name='name',
        ),
        migrations.RemoveField(
            model_name='imageview',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='imageview',
            name='viewController',
        ),
        migrations.RemoveField(
            model_name='imageview',
            name='width',
        ),
        migrations.RemoveField(
            model_name='imageview',
            name='x',
        ),
        migrations.RemoveField(
            model_name='imageview',
            name='y',
        ),
        migrations.RemoveField(
            model_name='imageview',
            name='z',
        ),
        migrations.RemoveField(
            model_name='label',
            name='color',
        ),
        migrations.RemoveField(
            model_name='label',
            name='height',
        ),
        migrations.RemoveField(
            model_name='label',
            name='id',
        ),
        migrations.RemoveField(
            model_name='label',
            name='name',
        ),
        migrations.RemoveField(
            model_name='label',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='label',
            name='viewController',
        ),
        migrations.RemoveField(
            model_name='label',
            name='width',
        ),
        migrations.RemoveField(
            model_name='label',
            name='x',
        ),
        migrations.RemoveField(
            model_name='label',
            name='y',
        ),
        migrations.RemoveField(
            model_name='label',
            name='z',
        ),
        migrations.AddField(
            model_name='button',
            name='view_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vision.View'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageview',
            name='view_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vision.View'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='view_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vision.View'),
            preserve_default=False,
        ),
    ]
