# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0013_auto_20171027_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=40)),
                ('height', models.IntegerField(default=40)),
                ('z', models.IntegerField(default=-1)),
                ('color', models.CharField(default='#efeff4', max_length=7)),
                ('viewController', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.ViewController')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='view',
            name='viewController',
        ),
        migrations.RemoveField(
            model_name='button',
            name='view_ptr',
        ),
        migrations.RemoveField(
            model_name='imageview',
            name='view_ptr',
        ),
        migrations.RemoveField(
            model_name='label',
            name='view_ptr',
        ),
        migrations.AddField(
            model_name='button',
            name='color',
            field=models.CharField(default='#efeff4', max_length=7),
        ),
        migrations.AddField(
            model_name='button',
            name='height',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='button',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='button',
            name='name',
            field=models.CharField(default='Button', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='button',
            name='viewController',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.ViewController'),
        ),
        migrations.AddField(
            model_name='button',
            name='width',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='button',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='button',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='button',
            name='z',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='imageview',
            name='color',
            field=models.CharField(default='#efeff4', max_length=7),
        ),
        migrations.AddField(
            model_name='imageview',
            name='height',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='imageview',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageview',
            name='name',
            field=models.CharField(default='ImageView', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageview',
            name='viewController',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.ViewController'),
        ),
        migrations.AddField(
            model_name='imageview',
            name='width',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='imageview',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageview',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageview',
            name='z',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(default='#efeff4', max_length=7),
        ),
        migrations.AddField(
            model_name='label',
            name='height',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='label',
            name='id',
            field=models.AutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='name',
            field=models.CharField(default='Header', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='viewController',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.ViewController'),
        ),
        migrations.AddField(
            model_name='label',
            name='width',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='label',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='label',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='label',
            name='z',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
