# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0016_auto_20171027_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcontroller',
            name='initial',
            field=models.BooleanField(default=False),
        ),
    ]
