# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0017_viewcontroller_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default action', max_length=50)),
                ('actionType', models.CharField(choices=[('v', 'Goto ViewController')], max_length=1)),
                ('targetViewController', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.ViewController')),
            ],
        ),
    ]
