# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0018_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.Action'),
        ),
        migrations.AddField(
            model_name='container',
            name='click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.Action'),
        ),
        migrations.AddField(
            model_name='imageview',
            name='click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.Action'),
        ),
        migrations.AddField(
            model_name='label',
            name='click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.Action'),
        ),
    ]
