# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0019_auto_20171027_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='button',
            old_name='click',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='click',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='imageview',
            old_name='click',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='click',
            new_name='action',
        ),
    ]
