# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0021_auto_20171027_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='layoutType',
            field=models.CharField(choices=[('f', 'Fixed x,y based layout'), ('v', 'Vertical layout'), ('h', 'horizontal layout')], default='f', max_length=1),
        ),
    ]
