# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0022_container_layouttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='anchor',
            field=models.CharField(choices=[('m', 'middle'), ('s', 'start'), ('e', 'end')], default='m', max_length=1),
        ),
    ]
