# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagevision', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('filename',)},
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='imagevision.Tag'),
        ),
    ]
