# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagevision', '0002_auto_20180615_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_image_related_+', to='imagevision.Image'),
        ),
    ]
