# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 14:30
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('B', 'Background'), ('I', 'Image'), ('U', 'User')], default='B', max_length=1)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('image', models.FileField(upload_to='uploads/')),
                ('x_offset', models.IntegerField()),
                ('y_offset', models.IntegerField()),
            ],
            options={
                'ordering': ('name', 'type'),
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenRelation',
            fields=[
                ('screen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='screens.Screen')),
                ('level', models.IntegerField()),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='screens.Layer')),
            ],
        ),
    ]
