# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0002_auto_20180817_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='x_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='layer',
            name='y_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='screenrelation',
            name='layer',
        ),
        migrations.AddField(
            model_name='screenrelation',
            name='layer',
            field=models.ManyToManyField(to='screens.Layer'),
        ),
        migrations.RemoveField(
            model_name='screenrelation',
            name='screen',
        ),
        migrations.AddField(
            model_name='screenrelation',
            name='screen',
            field=models.ManyToManyField(to='screens.Screen'),
        ),
    ]
