# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-20 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0006_auto_20180820_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutScreenRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('col', models.IntegerField(default=0)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screens.Layout')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screens.Screen')),
            ],
        ),
    ]
