# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-21 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0008_layoutrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='layer',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
